$(function(){
    $('#home').load('/frontend/html/home.html');
    $('#appointment').load('/frontend/html/appointment.html');
    $('#services').load('/frontend/html/services.html');
    $('#advice').load('/frontend/html/advice.html');
    $('#agenda').load('/frontend/html/agenda.html');
    $('#oldagenda').load('/frontend/html/oldagenda.html');
    $('#login').load('/frontend/html/login.html');
    $('#register').load('/frontend/html/register.html');
});